const Koa = require('koa')
const json = require('koa-json')
const logger = require('koa-logger')
const user = require('./ServerMYSQL/routes/user.js')
const test = require('./ServerMYSQL/routes/test.js')
const todolist = require('./ServerMYSQL/routes/todolist.js')
const path = require('path')
const serve = require('koa-static')
const historyApiFallback = require('koa2-history-api-fallback')
const koaRouter = require('koa-router')
const koaBodyparser = require('koa-bodyparser')
const app = new Koa()
const router = koaRouter()
app.use(koaBodyparser())
app.use(json())
router.use('/auth', user.routes())
router.use('/test', test.routes())
router.use('/api', todolist.routes())
app.use(router.routes())
app.use(historyApiFallback())
app.use(serve(path.resolve('./dist')))
app.use(logger())
app.use(async (ctx, next) => {
  const start = new Date()
  await next()
  const ms = new Date() - start
  console.log(`${ctx.method} ${ctx.url} - ${ms}ms`) // 输出请求响应结果
})

app.listen(8889, () => {
  console.log('[Server] starting at http://localhost:8889/')
})
