const Koa = require('koa')
const json = require('koa-json')
const logger = require('koa-logger')
const path = require('path')
const serve = require('koa-static')
const historyApiFallback = require('koa2-history-api-fallback')
const koaRouter = require('koa-router')
const koaBodyparser = require('koa-bodyparser')
// const easyMonitor = require('easy-monitor')
// easyMonitor('Mercury')
const app = new Koa()
const router = koaRouter()
app.use(koaBodyparser())
app.use(json())
app.use(router.routes())
app.use(historyApiFallback())
app.use(serve(path.resolve('./dist')))
app.use(logger())
app.use(async (ctx, next) => {
  const start = new Date()
  await next()
  const ms = new Date() - start
  console.log(`${ctx.method} ${ctx.url} - ${ms}ms`) // 输出请求响应结果
})
console.log('========启动mongodb数据库')
let user = require('./ServiceMongodb/api/user.js')
let todolist = require('./ServiceMongodb/api/todolist.js')
let test = require('./ServiceMongodb/api/testAPI.js')
router.use('/auth', user.routes())
router.use('/api', todolist.routes())
router.use('/test', test.routes())
const {connect, initSchemas} = require('./ServiceMongodb/database/init.js')
connect()
initSchemas()
app.listen(8889, () => {
  console.log('[Server] starting at http://localhost:8889/')
})
